server:
  port: 80
domains:
  user:
    url: 'http://localhost:8080'
  article:
    url: 'http://localhost:8000'
  sub-contents:
    url: 'http://52.78.115.142:3001'
jwt:
  secret: 'secret-64-byte-minimum-secret-key-which-must-be-long-enough-for-hmac'
logging:
  level:
    com.ninedocs.serviceaggregator: DEBUG
