server:
  port: 80
spring:
  application:
    name: 'service-aggregator'
  profiles:
    active: 'local'
springdoc:
  swagger-ui:
    path: '/swagger'
    disable-swagger-default-url: true
    operations-sorter: 'alpha'
    tags-sorter: 'alpha'
