server:
  port: 8080
domains:
  user:
    url: ${USER_URL}
  article:
    url: ${ARTICLE_URL}
  sub-contents:
    url: ${SUB_CONTENTS_URL}
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    root: WARN
