domains:
  user:
    url: 'http://localhost:8001'
  article:
    url: 'http://localhost:8000'
jwt:
  secret: 'secret-64-byte-minimum-secret-key-which-must-be-long-enough-for-hmac'
logging:
  level:
    com.ninedocs.serviceaggregator: DEBUG
